/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_sds_mhs_android_BPAlgorithm
#define _Included_sds_mhs_android_BPAlgorithm
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_samsung_sds_mhs_android_BPAlgorithm
 * Method:    getPrediction
 * Signature: (DDIID[D[D[D[D[DII[DII[D)V
 */
JNIEXPORT char JNICALL Java_com_samsung_sds_mhs_android_BPAlgorithm_estimateBP
(JNIEnv *env, jobject obj, jintArray data,jshort num_data,jshortArray sbp, jshortArray dbp, jshortArray hr, jdoubleArray feat1, jdoubleArray feat2, jdoubleArray feat3, jdoubleArray feat4, jchar reset);

#ifdef __cplusplus
}
#endif
#endif
